/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 2dea74f0cf9db77d6382a7368f3f837d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		DB: D1Database;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
