import type { Metadata } from "next";
import RootLayout from "./layout-inner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic
export const dynamic = "force-static";

export default RootLayout;
