services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v4.15.5
    ports:
      - "8080:8080"
    volumes:
      - ./openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      URL: openapi.yaml
  redoc:
    image: redocly/redoc
    ports:
      - 8081:80
    volumes:
      - ./openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      SPEC_URL: openapi.yaml
