/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/users": {
    get: operations["listUsers"];
    post: operations["createUser"];
  };
  "/users/{id}": {
    get: operations["getUser"];
  };
}

export interface components {
  schemas: {
    User: {
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example john */
      username?: string;
      firstName?: string;
      lastName?: string;
      email?: string;
      password?: string;
      phone?: string;
      /**
       * Format: int32
       * @description User Status
       */
      userStatus?: number;
    };
  };
}

export interface operations {
  listUsers: {
    responses: {
      /** A paged array of users */
      200: {
        content: {
          "application/json": components["schemas"]["User"][];
        };
      };
    };
  };
  createUser: {
    responses: {
      /** A paged array of users */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["User"];
      };
    };
  };
  getUser: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** A paged array of users */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
}

export interface external {}
