name: next-trpc-stack
on:
  push:
    paths:
      - next-trpc-stack/**
      - .github/**
    branches:
      - main
  pull_request:
    paths:
      - next-trpc-stack/**
      - .github/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: next-trpc-stack
    strategy:
      matrix:
        node-version:
          - 16.x
          - 17.x
          - 18.x
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: next-trpc-stack/pnpm-lock.yaml
      - run: pnpm i --frozen-lockfile
      - run: pnpm codegen
      - run: pnpm lint:ci
      - run: pnpm build
      - run: docker-compose up db -d
      - run: pnpm test
