name: remix-sandbox
on:
  push:
    paths:
      - remix-sandbox/**
      - .github/**
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: remix-sandbox
    strategy:
      matrix:
        node-version:
          - 16.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          # cache: npm
          # cache-dependency-path: remix-sandbox/package-lock.json
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run check:all
      - run: npm run build
      # - run: npm test
