name: pandacss-sandbox
on:
  push:
    paths:
      - pandacss-sandbox/**
      - .github/**
    branches:
      - main
  pull_request:
    paths:
      - pandacss-sandbox/**
      - .github/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pandacss-sandbox
    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
          - 20.x
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # cache: pnpm
          cache-dependency-path: pandacss-sandbox/pnpm-lock.yaml
      - run: pnpm i --frozen-lockfile
      - run: pnpm tsc --noEmit
      - run: pnpm build
      - run: pnpm test
