name: remix-sandbox
on:
  push:
    paths:
      - remix-sandbox/**
      - .github/**
    branches:
      - main
  pull_request:
    paths:
      - remix-sandbox/**
      - .github/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: remix-sandbox
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 17.x
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable pnpm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: remix-sandbox/pnpm-lock.yaml
      - run: pnpm i
      - run: cp app/env.sample.ts app/env.ts
      - run: pnpm run check:all
      - run: pnpm run build
      # - run: npm test
